packages:
  - 'frontend'
  - 'backend'
  - 'shared'
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msgpackr-extract
  - prisma
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
